# Navigation for "onDemand/"
ignore:
  - Apps/* # this contains the app cards which are embedded into "available.md"

nav:
 - ondemand.md
 - ood_file_manager.md
 - hpc_desktop.md
 - ood_shell.md
 - available_apps.md