# navigation for "getting_started/"
nav:
  - overview.md
  - access
  - Cluster Traffic:
      - Current Utilisation: current_utilisation.md
      - Queue and Availability: queue_and_availability.md
  - software
  - Running Jobs: running
